services:
  - type: web
    name: pleasantonstudentpro-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: GEMINI_API_KEY
        value: AIzaSyAkkTVjbQ9Uv2DxLA6m4swvl-KdHOavYdA
    healthCheckPath: /health
    autoDeploy: true 