services:
  - type: web
    name: pleasantonstudentpro-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://pleasantonstudentpro:pleasantonstudentpro@cluster0.mongodb.net/pleasantonstudentpro?retryWrites=true&w=majority
    healthCheckPath: /health
    autoDeploy: true 