services:
  - type: web
    name: pleasantonstudentpro-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true 